name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  # pull_request:
  #   branches: [ "master" ]

jobs:
  # check-changed-path:
  #   runs-on: ubuntu-latest
  #   outputs:
  #     output1: ${{ steps.filter.outputs.filters }}
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: dorny/paths-filter@v2
  #       id: filter
  #       with:
  #         filters: |
  #           8.0:
  #             - '8.0/**'
  #           8.1:
  #             - '8.1/**'

  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.filter.outputs.filters }}
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            8.0:
              - '8.0/**'
            8.1:
              - '8.1/**'
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      # - name: Build and push
      #   if: jobs.check-changed-path.steps.filter.outputs.filters == 'true'
      #   uses: docker/build-push-action@v4
      #   with:
      #     context: "{{defaultContext}}:mysubdir"
      #     push: true
      #     tags: lanuma/app:latest
      
