name: Docker Image Build and Push

on:
  push:
    branches: [ "master" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.filter.outputs.filters }}
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
        # with:
        #   ref: ${{ github.event.pull_request.head.sha }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            wolukosong:
              - '8.0/**'
            wolusiji:
              - '8.1/**'
      - name: run output
        run: |
          echo "${{steps.filter.outputs.*}}"
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push image php 8.0
        if: steps.filter.outputs.wolukosong == 'true'
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:8.0"
          platforms: linux/amd64,linux/arm64
          push: true
          tags: lanuma/php:8.0
      - name: Build and push image php 8.1
        if: steps.filter.outputs.wolusiji == 'true'
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:8.1"
          platforms: linux/amd64,linux/arm64
          push: true
          tags: lanuma/php:8.1,lanuma/php:latest
      
